const products = [
  {name:'Wireless noise-cancelling headphones',price:34.99,rating:'4.7',reviews:328,badge:'TRENDING',delivery:'Estimated delivery 3–5 days',image:'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=700&q=82'},
  {name:'Portable LED ambient table lamp',price:22.49,rating:'4.8',reviews:174,badge:'POPULAR',delivery:'Estimated delivery 2–4 days',image:'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=700&q=82'},
  {name:'Smart fitness watch with activity tracking',price:39.95,rating:'4.6',reviews:512,badge:'BEST SELLER',delivery:'Estimated delivery 3–6 days',image:'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=700&q=82'},
  {name:'Minimal insulated travel bottle',price:18.99,rating:'4.9',reviews:91,badge:'NEW',delivery:'Estimated delivery 2–5 days',image:'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=700&q=82'},
  {name:'Compact cordless handheld vacuum',price:42.99,rating:'4.5',reviews:207,badge:'POPULAR',delivery:'Estimated delivery 4–7 days',image:'https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&w=700&q=82'},
  {name:'Modern desk organiser set',price:16.50,rating:'4.7',reviews:68,badge:'',delivery:'Estimated delivery 3–5 days',image:'https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=700&q=82'},
  {name:'Everyday crossbody travel bag',price:27.99,rating:'4.8',reviews:145,badge:'TRENDING',delivery:'Estimated delivery 3–6 days',image:'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=700&q=82'},
  {name:'Ceramic aroma diffuser',price:24.95,rating:'4.6',reviews:118,badge:'',delivery:'Estimated delivery 2–5 days',image:'https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=700&q=82'}
];
const grid=document.getElementById('productGrid');let basket=0;
function render(list){grid.innerHTML=list.map((p,i)=>`<article class="product-card"><div class="product-image"><img src="${p.image}" alt="${p.name}" loading="lazy">${p.badge?`<span class="badge">${p.badge}</span>`:''}<button class="heart" aria-label="Save ${p.name}">♡</button></div><div class="product-info"><div class="product-name">${p.name}</div><div class="rating"><strong>★★★★★</strong> ${p.rating} (${p.reviews})</div><div class="price-row"><span class="price">£${p.price.toFixed(2)}</span><button class="add" data-i="${i}">ADD</button></div><div class="delivery">${p.delivery}</div></div></article>`).join('');bindButtons()}
function bindButtons(){document.querySelectorAll('.add').forEach(b=>b.onclick=()=>{basket++;document.getElementById('basketCount').textContent=basket;toast('Added to your bag')});document.querySelectorAll('.heart').forEach(b=>b.onclick=()=>{b.textContent=b.textContent==='♡'?'♥':'♡';toast(b.textContent==='♥'?'Saved for later':'Removed from saved')})}
function toast(text){const t=document.getElementById('toast');t.textContent=text;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),1800)}
document.getElementById('searchForm').addEventListener('submit',e=>{e.preventDefault();const q=document.getElementById('searchInput').value.trim().toLowerCase();if(!q){render(products);return}const matches=products.filter(p=>p.name.toLowerCase().includes(q));render(matches);document.getElementById('trending').scrollIntoView();toast(matches.length?`${matches.length} result${matches.length===1?'':'s'} found`:'No demo products match yet')});
render(products);